# -*- coding: utf-8 -*-
"""MOVIE RECOMMENDATION SYSTEM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b0gbubf6dV8V6eIXahdQEFVByn7tWKJ-
"""

pip install pandas numpy scikit-learn

import pandas as pd
ratings = pd.read_csv('u.data', sep='\t', names=['user_id', 'movie_id', 'rating','timestamp'])
movies =pd.read_csv('u.item', sep='|', encoding='latin-1', names=['movie_id','title'],usecols=[0,1])
data = pd.merge(ratings, movies, on='movie_id')
data.head()

user_movie_matrix = data.pivot_table(index='user_id', columns='title', values='rating')

target_movie ="Star Wars (1977)"
target_ratings = user_movie_matrix[target_movie]
similar_movies = user_movie_matrix.corrwith(target_ratings)
corr_df = pd.DataFrame(similar_movies, columns=['Correlation'])
corr_df.dropna(inplace=True)
rating_counts = data.groupby('title')['rating'].count()
corr_df = corr_df.join(rating_counts)
corr_df.columns = ['Correlation', 'RatingCount']
corr_df[corr_df['RatingCount'] > 50].sort_values('Correlation',ascending=False).head(10)

def recommend(movie_name, min_ratings=50):
    movie_ratings = user_movie_matrix[movie_name]
    similar = user_movie_matrix.corrwith(movie_ratings)

    corr_df = pd.DataFrame(similar, columns=['Correlation'])
    corr_df.dropna(inplace=True)

    rating_counts = data.groupby('title')['rating'].count()

    corr_df = corr_df.join(rating_counts)
    corr_df.rename(columns={'rating': 'RatingCount'}, inplace=True)  # ✅ Correct column name

    return corr_df[corr_df['RatingCount'] > min_ratings].sort_values('Correlation', ascending=False).head(10)

recommend("Toy Story (1995)")